name: Build and run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   

    - name: build
      working-directory: ./Sender/src/
      run: gcc -DMAIN -Wall -Wextra -o testchecker *.c

    - name: run
      working-directory: ./Sender/src/
      run: ./testchecker 